server:
  port: 9090

spring:
  application:
    name: spring-securty
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: root
    password: hSelMan%231?!
  jpa:
    hibernate:
      ddl-auto: update


security:
  jwt :
    secret : "AJSFDASLKFHALKJHFAJLKHFAJKHFAJFHAFALfsdafsfd"